// Contract export: the golden file, determinism, cue vet against the
// meta-schema, and the --docuconf-export entry point.
#include <gtest/gtest.h>

#include "test_util.hpp"

using testutil::Gateway;

namespace {

std::string golden_path() { return std::string(DOCUCONF_SOURCE_DIR) + "/tests/golden/gateway.cue"; }

TEST(Export, MatchesGolden) {
    Gateway g;
    std::string got = g.config.export_cue();
    if (const char* u = std::getenv("UPDATE_GOLDEN"); u && std::string(u) == "1") {
        std::ofstream(golden_path()) << got;
    }
    EXPECT_EQ(testutil::without_generator_version(got), testutil::without_generator_version(testutil::read(golden_path())))
        << "re-run with UPDATE_GOLDEN=1 to update the golden file";
}

TEST(Export, GoldenComparisonIgnoresOnlyTheGeneratorVersion) {
    Gateway g;
    std::string got = g.config.export_cue();
    std::string bumped = std::regex_replace(got, std::regex(R"(version: +"[0-9][^"]*")"), "version: \"99.0.0\"");
    ASSERT_NE(bumped, got);
    EXPECT_EQ(testutil::without_generator_version(bumped), testutil::without_generator_version(got));
    std::string renamed = std::regex_replace(got, std::regex(R"(language: "cpp")"), "language: \"c\"");
    ASSERT_NE(renamed, got);
    EXPECT_NE(testutil::without_generator_version(renamed), testutil::without_generator_version(got));
}

TEST(Export, IsDeterministic) {
    Gateway a, b;
    EXPECT_EQ(a.config.export_cue(), b.config.export_cue());
    EXPECT_EQ(a.config.export_cue(), a.config.export_cue());
}

TEST(Export, HeaderPackageAndImport) {
    Gateway g;
    std::string cue = g.config.export_cue();
    EXPECT_EQ(cue.rfind("// Code generated by docuconf. DO NOT EDIT.\npackage gateway\n\nimport \"docuconf.dev/contract\"\n\ncontract.#Contract & {", 0), 0u);
    EXPECT_NE(cue.find("language: \"cpp\""), std::string::npos);
}

TEST(Export, NarrowIntegerTypesExportTheirRange) {
    Gateway g;
    auto c = g.config.export_json();
    EXPECT_EQ(c["vars"]["PORT"]["min"], 1);
    EXPECT_EQ(c["vars"]["PORT"]["max"], 65535);
    EXPECT_EQ(c["vars"]["CACHE__SIZE"]["min"], 0);
    EXPECT_EQ(c["vars"]["CACHE__SIZE"]["max"], 4294967295LL);
    EXPECT_EQ(c["vars"]["EXTRA_PORTS"]["itemMin"], 1);
    EXPECT_EQ(c["vars"]["EXTRA_PORTS"]["itemMax"], 65535);
    EXPECT_EQ(c["vars"]["SHARDS"]["itemMin"], 0);
    EXPECT_EQ(c["vars"]["SHARDS"]["itemMax"], 1023);
    EXPECT_FALSE(c["vars"]["MEMORY_LIMIT"].contains("max"));
}

TEST(Export, RequiredUnlessOptionalOrDefaulted) {
    Gateway g;
    auto c = g.config.export_json();
    EXPECT_EQ(c["vars"]["POD_NAMESPACE"].value("required", false), true);
    EXPECT_EQ(c["vars"]["DATABASE_URL"].value("required", false), true);
    EXPECT_FALSE(c["vars"]["MEMORY_LIMIT"].contains("required"));
    EXPECT_FALSE(c["vars"]["PORT"].contains("required"));
}

TEST(Export, VetsAgainstTheMetaSchema) {
    Gateway g;
    std::optional<std::string> err;
    try {
        err = testutil::cue_vet(g.config.export_cue());
    } catch (const std::runtime_error& e) {
        GTEST_SKIP() << e.what();
    }
    EXPECT_FALSE(err) << *err;
}

TEST(Export, TheContractLoadsInContractFirstMode) {
    // The exported contract, read back as JSON, accepts and rejects the
    // same values as the declaration.
    Gateway g;
    // Variables only: contract-first mode would read the file inputs too,
    // and the files tests cover those.
    auto exported = nlohmann::json::parse(g.config.export_json().dump());
    exported.erase("files");
    auto contract = docuconf::Contract::from_json(exported);
    docuconf::Env env = {{"POD_NAMESPACE", "prod"},
                         {"PARTNER_KEYSTORE_PASSWORD", "pw"},
                         {"DATABASE_URL", "postgres://db/app"},
                         {"ALLOWED_ORIGINS", "https://a.example.com,https://b.example.com"},
                         {"SHARDS", "1;2;3"},
                         {"REQUEST_TIMEOUT", "1m30s"}};
    auto values = contract.load(env);
    EXPECT_EQ(values.get("PORT")->as_int(), 8080);
    EXPECT_EQ(values.to_json()["REQUEST_TIMEOUT"], "1m30s");
    EXPECT_EQ(values.to_json()["SHARDS"], json::parse("[1,2,3]"));
    EXPECT_EQ(values.to_redacted_json()["DATABASE_URL"], "***");
    env["PORT"] = "70000";
    try {
        contract.load(env);
        FAIL() << "expected out_of_range";
    } catch (const docuconf::ValidationError& e) {
        EXPECT_EQ(e.codes_for("PORT"), std::vector<docuconf::Code>{docuconf::Code::OutOfRange});
    }
}

TEST(Export, FlagWritesTheContractWithoutReadingTheEnvironment) {
    testutil::TempDir dir;
    Gateway g;
    std::string out = dir.str() + "/contract.cue";
    // Nothing required is set, and PORT is invalid: export does not care.
    ::setenv("PORT", "not-a-port", 1);
    std::vector<const char*> argv = {"gateway", "--docuconf-export", out.c_str()};
    int code = -1;
    std::ostringstream err;
    EXPECT_TRUE(g.config.parse_or_exit(static_cast<int>(argv.size()), argv.data(), code, err));
    ::unsetenv("PORT");
    EXPECT_EQ(code, 0) << err.str();
    EXPECT_EQ(testutil::read(out), g.config.export_cue());
}

TEST(Export, FlagWithEqualsAndStdout) {
    Gateway g;
    std::vector<const char*> argv = {"gateway", "--docuconf-export=-"};
    testing::internal::CaptureStdout();
    int code = -1;
    std::ostringstream err;
    EXPECT_TRUE(g.config.parse_or_exit(static_cast<int>(argv.size()), argv.data(), code, err));
    std::string printed = testing::internal::GetCapturedStdout();
    EXPECT_EQ(code, 0);
    EXPECT_EQ(printed, g.config.export_cue());
}

}  // namespace
